from ..js_object import JsObject
from .document import JsDocument


class JsWindow(JsObject):
    applicationCache: JsObject
    closed: JsObject
    console: JsObject
    customElements: JsObject
    defaultStatus: JsObject
    devicePixelRatio: JsObject
    dialogArguments: JsObject
    document: JsDocument
    event: JsObject
    frameElement: JsObject
    frames: JsObject
    fullScreen: JsObject
    history: JsObject
    innerHeight: JsObject
    innerWidth: JsObject
    length: JsObject
    localStorage: JsObject
    location: JsObject
    locationbar: JsObject
    menubar: JsObject
    mozInnerScreenX: JsObject
    mozInnerScreenY: JsObject
    mozPaintCount: JsObject
    name: JsObject
    navigator: JsObject
    onappinstalled: JsObject
    onbeforeinstallprompt: JsObject
    ondevicemotion: JsObject
    ondeviceorientation: JsObject
    ondeviceorientationabsolute: JsObject
    ondragdrop: JsObject
    ongamepadconnected: JsObject
    ongamepaddisconnected: JsObject
    onvrdisplayactivate: JsObject
    onvrdisplayblur: JsObject
    onvrdisplayconnect: JsObject
    onvrdisplaydeactivate: JsObject
    onvrdisplaydisconnect: JsObject
    onvrdisplayfocus: JsObject
    onvrdisplaypointerrestricted: JsObject
    onvrdisplaypointerunrestricted: JsObject
    onvrdisplaypresentchange: JsObject
    opener: JsObject
    outerHeight: JsObject
    outerWidth: JsObject
    pageXOffset: JsObject
    pageYOffset: JsObject
    parent: JsObject
    personalbar: JsObject
    screen: JsObject
    screenLeft: JsObject
    screenTop: JsObject
    screenX: JsObject
    screenY: JsObject
    scrollbars: JsObject
    scrollMaxX: JsObject
    scrollMaxY: JsObject
    scrollX: JsObject
    scrollY: JsObject
    self: JsObject
    sessionStorage: JsObject
    sidebar: JsObject
    speechSynthesis: JsObject
    status: JsObject
    statusbar: JsObject
    toolbar: JsObject
    top: JsObject
    visualViewport: JsObject
    window: JsObject

    alert: JsObject
    back: JsObject
    blur: JsObject
    cancelAnimationFrame: JsObject
    cancelIdleCallback: JsObject
    captureEvents: JsObject
    clearImmediate: JsObject
    close: JsObject
    confirm: JsObject
    convertPointFromNodeToPage: JsObject
    convertPointFromPageToNode: JsObject
    dump: JsObject
    find: JsObject
    focus: JsObject
    forward: JsObject
    getComputedStyle: JsObject
    getDefaultComputedStyle: JsObject
    getSelection: JsObject
    matchMedia: JsObject
    moveBy: JsObject
    moveTo: JsObject
    open: JsObject
    openDialog: JsObject
    postMessage: JsObject
    print: JsObject
    prompt: JsObject
    releaseEvents: JsObject
    requestAnimationFrame: JsObject
    requestFileSystem: JsObject
    requestIdleCallback: JsObject
    resizeBy: JsObject
    resizeTo: JsObject
    scroll: JsObject
    scrollBy: JsObject
    scrollByLines: JsObject
    scrollByPages: JsObject
    scrollTo: JsObject
    setCursor: JsObject
    setImmediate: JsObject
    showDirectoryPicker: JsObject
    showModalDialog: JsObject
    showOpenFilePicker: JsObject
    showSaveFilePicker: JsObject
    sizeToContent: JsObject
    stop: JsObject
    updateCommands: JsObject

    event: JsObject
    afterprint: JsObject
    animationcancel: JsObject
    animationend: JsObject
    animationiteration: JsObject
    beforeprint: JsObject
    beforeunload: JsObject
    blur: JsObject
    copy: JsObject
    cut: JsObject
    DOMContentLoaded: JsObject
    error: JsObject
    focus: JsObject
    hashchange: JsObject
    languagechange: JsObject
    load: JsObject
    message: JsObject
    messageerror: JsObject
    offline: JsObject
    online: JsObject
    orientationchange: JsObject
    pagehide: JsObject
    pageshow: JsObject
    paste: JsObject
    popstate: JsObject
    rejectionhandled: JsObject
    storage: JsObject
    transitioncancel: JsObject
    unhandledrejection: JsObject
    unload: JsObject
    vrdisplayconnect: JsObject
    vrdisplaydisconnect: JsObject
    vrdisplaypresentchange: JsObject
    EventTarget: JsObject
